/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Health
         * @description Report API liveness and LLM / detector / data availability.
         */
        get: operations["get_health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scene": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scene
         * @description Base and zones.
         */
        get: operations["get_scene_api_scene_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Images
         * @description All frames sorted by capture time.
         */
        get: operations["list_images_api_images_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/{image_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Image File
         * @description Raw frame image (no filesystem paths leak to the client).
         */
        get: operations["get_image_file_api_images__image_id__file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Analysis
         * @description Analyze one frame (reuses the latest result unless `force_refresh`).
         */
        post: operations["create_analysis_api_analyses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyses/{analysis_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Analysis
         * @description Return a finished analysis.
         */
        get: operations["get_analysis_api_analyses__analysis_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Analysis
         * @description Everything the pipeline produced for one frame. Self-contained so it can be replayed.
         */
        Analysis: {
            /** Id */
            id: string;
            /** Image Id */
            image_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "done" | "error";
            image: components["schemas"]["ImageMeta"] | null;
            scene: components["schemas"]["Scene"] | null;
            /** Steps */
            steps: components["schemas"]["StepResult"][];
            /** Detections */
            detections: components["schemas"]["Detection"][];
            /** Track Snapshots */
            track_snapshots: components["schemas"]["TrackSnapshot"][];
            /** Matches */
            matches: components["schemas"]["TrackMatch"][];
            /** Motions */
            motions: components["schemas"]["MotionProfile"][];
            /** Reports */
            reports: components["schemas"]["ReportClaim"][];
            /** Report Assessments */
            report_assessments: components["schemas"]["ReportAssessment"][];
            /** Risks */
            risks: components["schemas"]["VehicleRisk"][];
            brief: components["schemas"]["Brief"] | null;
            /** Timings Ms */
            timings_ms: {
                [key: string]: number;
            };
            token_usage: components["schemas"]["TokenUsage"];
        };
        /**
         * AnalysisCreate
         * @description Request body for `POST /api/analyses`.
         */
        AnalysisCreate: {
            /** Image Id */
            image_id: string;
            /**
             * Force Refresh
             * @default false
             */
            force_refresh: boolean;
        };
        /**
         * AnalysisCreated
         * @description Response of `POST /api/analyses`.
         */
        AnalysisCreated: {
            /** Analysis Id */
            analysis_id: string;
        };
        /**
         * Base
         * @description The protected base.
         */
        Base: {
            /** Name */
            name: string;
            position: components["schemas"]["LatLon"];
        };
        /**
         * Brief
         * @description Operator-facing risk brief for one frame.
         */
        Brief: {
            /** Image Id */
            image_id: string;
            /**
             * Level
             * @enum {string}
             */
            level: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            /** Headline */
            headline: string;
            /** Summary */
            summary: string;
            /** Vehicles */
            vehicles: components["schemas"]["VehicleBriefLine"][];
            /** Report Notes */
            report_notes: string[];
            /** Uncertainties */
            uncertainties: string[];
            /**
             * Recommended Action
             * @enum {string}
             */
            recommended_action: "MONITOR" | "VERIFY" | "ESCALATE";
            /** Evidence Ids */
            evidence_ids: string[];
            /**
             * Generated By
             * @enum {string}
             */
            generated_by: "llm" | "fallback";
        };
        /**
         * ComponentStatus
         * @description Availability of one external dependency.
         */
        ComponentStatus: {
            /** Available */
            available: boolean;
            /** Detail */
            detail: string;
        };
        /**
         * Detection
         * @description One detected vehicle. Geo fields are filled by the georeference step.
         */
        Detection: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Confidence */
            confidence: number;
            /** Bbox */
            bbox: [
                number,
                number,
                number,
                number
            ];
            /** Center Px */
            center_px: [
                number,
                number
            ];
            position: components["schemas"]["LatLon"] | null;
            /** Distance To Base M */
            distance_to_base_m: number | null;
            /** Bearing From Base Deg */
            bearing_from_base_deg: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Health
         * @description Liveness plus the state of every dependency with a fallback.
         */
        Health: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
            llm: components["schemas"]["ComponentStatus"];
            detector: components["schemas"]["ComponentStatus"];
            data: components["schemas"]["ComponentStatus"];
        };
        /**
         * ImageMeta
         * @description One drone frame: size in pixels, capture time and ground corners.
         */
        ImageMeta: {
            /** Image Id */
            image_id: string;
            /** Width Px */
            width_px: number;
            /** Height Px */
            height_px: number;
            /** Capture Time */
            capture_time: string;
            /** Capture Min */
            capture_min: number;
            /** Corners */
            corners: {
                [key: string]: components["schemas"]["LatLon"];
            };
            /** Zone */
            zone: string | null;
        };
        /**
         * LatLon
         * @description WGS84 position in decimal degrees.
         */
        LatLon: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
        };
        /**
         * MotionProfile
         * @description Motion features of one track over the window before capture (AGENT_DESIGN §3 step 5).
         */
        MotionProfile: {
            /** Track Id */
            track_id: string;
            /** Points */
            points: components["schemas"]["TrackPoint"][];
            /** Path Km */
            path_km: number;
            /** Mean Speed Ms */
            mean_speed_ms: number;
            /** Last10 Speed Ms */
            last10_speed_ms: number;
            /** Heading Deg */
            heading_deg: number | null;
            /** Bearing To Base Deg */
            bearing_to_base_deg: number;
            /** Dist Now M */
            dist_now_m: number;
            /** Dist 30M Ago M */
            dist_30m_ago_m: number | null;
            /** Dist 60M Ago M */
            dist_60m_ago_m: number | null;
            /** Min Dist M */
            min_dist_m: number;
            /** Approach Rate M Per Min */
            approach_rate_m_per_min: number;
            /** Stops */
            stops: components["schemas"]["Stop"][];
            /** Zones Visited */
            zones_visited: string[];
            /** Eta To Base Min */
            eta_to_base_min: number | null;
        };
        /**
         * ReportAssessment
         * @description Verdict on one report relative to one frame's own sensor data.
         */
        ReportAssessment: {
            /** Report Id */
            report_id: string;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "CORROBORATED" | "CONTRADICTED" | "UNVERIFIED" | "IRRELEVANT";
            /** Reason */
            reason: string;
            /** Checks */
            checks: components["schemas"]["ReportCheck"][];
            /** Linked Detection Ids */
            linked_detection_ids: string[];
            /** Trust Weight */
            trust_weight: number;
        };
        /**
         * ReportCheck
         * @description One code-side comparison of a claim against our own data.
         */
        ReportCheck: {
            /**
             * Name
             * @enum {string}
             */
            name: "location" | "presence" | "type" | "activity" | "instructions";
            /**
             * Status
             * @enum {string}
             */
            status: "match" | "mismatch" | "unknown";
            /** Detail */
            detail: string;
        };
        /**
         * ReportClaim
         * @description Structured claim extracted from one free-text report. The text is untrusted.
         */
        ReportClaim: {
            /** Report Id */
            report_id: string;
            /** Time */
            time: string;
            /** Time Min */
            time_min: number;
            /** Source */
            source: string;
            /** Text */
            text: string;
            location: components["schemas"]["LatLon"] | null;
            /** Zone */
            zone: string | null;
            /** Vehicle Type */
            vehicle_type: string | null;
            /** Count */
            count: number | null;
            /** Color */
            color: string | null;
            /**
             * Activity
             * @default unknown
             * @enum {string}
             */
            activity: "moving" | "stationary" | "loading" | "unknown";
            /**
             * Claim Kind
             * @default OTHER
             * @enum {string}
             */
            claim_kind: "SIGHTING" | "ALL_CLEAR" | "FRIENDLY_PRESENCE" | "TRAFFIC_NORMAL" | "OTHER";
            /**
             * Extracted By
             * @default rules
             * @enum {string}
             */
            extracted_by: "llm" | "rules";
        };
        /**
         * RiskFactor
         * @description One rubric line contributing points to a vehicle score.
         */
        RiskFactor: {
            /** Name */
            name: string;
            /** Points */
            points: number;
            /** Detail */
            detail: string;
        };
        /**
         * Scene
         * @description Static geography of the day: base plus zones.
         */
        Scene: {
            base: components["schemas"]["Base"];
            /** Zones */
            zones: components["schemas"]["Zone"][];
        };
        /**
         * StepResult
         * @description Final state of one pipeline step, stored in the analysis.
         */
        StepResult: {
            /**
             * Step
             * @enum {string}
             */
            step: "load_frame" | "detect" | "georeference" | "match_tracks" | "analyze_motion" | "assess_reports" | "score_risk" | "write_brief";
            /** Index */
            index: number;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "done" | "warning" | "error";
            /** Summary */
            summary: string;
            /** Data */
            data: {
                [key: string]: unknown;
            };
            /** Warnings */
            warnings: string[];
            /** Duration Ms */
            duration_ms: number | null;
        };
        /**
         * Stop
         * @description A run of samples with speed below the stop threshold.
         *
         *     `duration_min` counts 5-minute sample slots (k samples -> 5k min), matching the organizer's
         *     example (12:10..12:45 at one spot = "40 dk").
         */
        Stop: {
            /** Start */
            start: string;
            /** Duration Min */
            duration_min: number;
            position: components["schemas"]["LatLon"];
            /** Zone */
            zone: string | null;
            /** Distance To Base M */
            distance_to_base_m: number;
        };
        /**
         * TokenUsage
         * @description LLM token counters for one analysis.
         */
        TokenUsage: {
            /**
             * Prompt Tokens
             * @default 0
             */
            prompt_tokens: number;
            /**
             * Completion Tokens
             * @default 0
             */
            completion_tokens: number;
            /**
             * Calls
             * @default 0
             */
            calls: number;
            /**
             * Cache Hits
             * @default 0
             */
            cache_hits: number;
        };
        /**
         * TrackMatch
         * @description Assignment of a detection to a track at capture time.
         */
        TrackMatch: {
            /** Detection Id */
            detection_id: string;
            /** Track Id */
            track_id: string | null;
            /** Distance M */
            distance_m: number | null;
            /** Second Best M */
            second_best_m: number | null;
            /** Second Best Track Id */
            second_best_track_id: string | null;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "high" | "medium" | "low" | "none";
        };
        /**
         * TrackPoint
         * @description One track sample.
         */
        TrackPoint: {
            /** Time */
            time: string;
            /** Time Min */
            time_min: number;
            position: components["schemas"]["LatLon"];
        };
        /**
         * TrackSnapshot
         * @description A track's interpolated position at capture time, if it falls inside the frame.
         */
        TrackSnapshot: {
            /** Track Id */
            track_id: string;
            position: components["schemas"]["LatLon"];
            /** Center Px */
            center_px: [
                number,
                number
            ];
            /** Matched Detection Id */
            matched_detection_id: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VehicleBriefLine
         * @description One sentence about one vehicle, with its evidence IDs.
         */
        VehicleBriefLine: {
            /** Detection Id */
            detection_id: string;
            /** Track Id */
            track_id: string | null;
            /**
             * Level
             * @enum {string}
             */
            level: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            /** Text */
            text: string;
            /** Evidence Ids */
            evidence_ids: string[];
        };
        /**
         * VehicleRisk
         * @description Rubric score (0-100) for one detected vehicle.
         */
        VehicleRisk: {
            /** Detection Id */
            detection_id: string;
            /** Track Id */
            track_id: string | null;
            /** Score */
            score: number;
            /**
             * Level
             * @enum {string}
             */
            level: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            /** Factors */
            factors: components["schemas"]["RiskFactor"][];
        };
        /**
         * Zone
         * @description A monitored zone, identified by name (as used in reports).
         */
        Zone: {
            /** Name */
            name: string;
            center: components["schemas"]["LatLon"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    get_scene_api_scene_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scene"];
                };
            };
        };
    };
    list_images_api_images_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageMeta"][];
                };
            };
        };
    };
    get_image_file_api_images__image_id__file_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                image_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_analysis_api_analyses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analysis_api_analyses__analysis_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Analysis"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
